set_default_level:
  name: Set default level
  description: Set the default log level for integrations.
  fields:
    level:
      name: Level
      description: Default severity level for all integrations.
      example: debug
      selector:
        select:
          options:
            - debug
            - info
            - warning
            - error
            - fatal
            - critical

set_level:
  name: Set level
  description: Set log level for integrations.
  fields:
    homeassistant.core:
      description:
        "Example on how to change the logging level for a Home Assistant Core
        integrations. Possible values are debug, info, warn, warning, error,
        fatal, critical."
      example: debug
    homeassistant.components.mqtt:
      description:
        "Example on how to change the logging level for an Integration. Possible
        values are debug, info, warn, warning, error, fatal, critical."
      example: warning
    custom_components.my_integration:
      description:
        "Example on how to change the logging level for a Custom Integration.
        Possible values are debug, info, warn, warning, error, fatal, critical."
      example: debug
    aiohttp:
      description:
        "Example on how to change the logging level for a Python module.
        Possible values are debug, info, warn, warning, error, fatal, critical."
      example: error
